name: null

channels:
  - conda-forge
  - defaults

dependencies:
  - hvplot=0.6
  - ipython-sql=0.3
  - matplotlib=3.3
  - nbdime=1.1
  - nodejs
  - pandas=1.1
  - pip=20.2
  - pip:
    - -r file:requirements.txt
  - python=3.8
  - jupyterlab=1.2
  - jupyterlab-git=0.9
