name: null

channels:
  - conda-forge
  - defaults

dependencies:
  - git=2.28
  - matplotlib=3.3
  - nodejs=14.9
  - pandas=1.1
  - pip=20.2
  - pip:
    - -r file:requirements.txt
  - python=3.8
  - jupyterlab=2.2
  - jupyterlab-git=0.21
  - xeus-python=0.8
